### ISSUE TITLE
Make Browser always open and not reset the session

### ISSUE THREAD

**Issue by ndeztea** [giorgiosironi/phpunit-selenium#280]
Hi Guys,

I have an issue, how the browser keep open after one of test finished or how to avoid resetting the sessions when new browser open to execute another test?

I will really happy if someone can help this.

Thx

**Comment by PatricB** [comment]
someone should close this...

**Comment by sushantbajra** [comment]
@ndeztea , I am going through the same issue. How did you solve it? Did you place $this->shareSession(true); in the setUp() ? It is not working for me

**Comment by giorgiosironi** [comment]
Here's a working example fo what you should do:
https://github.com/giorgiosironi/phpunit-selenium/blob/master/phpunit-selenium-bootstrap.php

**Comment by oliverkoenig** [comment]
It would be easy to change the behaviour of the Session class if the session creation would be done by a factory that could be overridden to inject one's own derived Session class. I tried to intercept the session creation at all places I could reach by overriding classes and methods, but still couldn't manage. After spending a whole day on this issue, in my despair I just wanted to get it to work and directly manipulated the code. http://stackoverflow.com/a/37900651/2290188
