### ISSUE TITLE
Dynamic setting of self::$browsers?

### ISSUE THREAD

**Issue by jlipps** [giorgiosironi/phpunit-selenium#337]
Having the $browsers array be static causes problems when trying to run test suites where the browsers to be run is dependent on some kind of external factor. See https://github.com/jlipps/sausage/issues/8 for an example.

Can we make this a non-static property? Or provide a non-static override for backwards compatibility?

**Comment by discopatrick** [comment]
@giorgiosironi Thanks for this info. So it seems that $browsers can either be set like a property, or be a method that returns the array. Good to know.

**Comment by jlipps** [comment]
Ah OK I didn't realize it could be a function as well. That should be fine then!
