### ISSUE TITLE
phpunit webdriver, config

### ISSUE THREAD

**Issue by kantim** [giorgiosironi/phpunit-selenium#345]
Hello, can you help me to understand config?

1) to version 3.7 could indicate any configuration
$ phpunit --config=/home/maxim/test/selenium/Config.php Search.php
PHPUnit 3.7.28 by Sebastian Bergmann.

.
Time: 5.37 seconds, Memory: 4.25Mb

he looks config:
<?php
class Config extends TestConfig
{
    protected $settings = array(
        'selenium_host'    => '127.0.0.1',
        'selenium_port'    => '4444',
        'selenium_browser' => 'firefox',
        'url'              => 'http://test.build.ru/',

2) In the new version phpunit wants xml

$ phpunit --version
PHPUnit 4.6.6 by Sebastian Bergmann and contributors.
$ phpunit --config=/home/maxim/test/selenium/Config.php Search.php
Could not load "/home/maxim/test/selenium/Config.php".
 
ParsePI: PI php never end ...
 
Start tag expected, '<' not found

3) I found in the article how to set parameters through configuration
https://phpunit.de/manual/4.6/en/appendixes.configuration.html#appendixes.configuration.selenium-rc

but I do not understand how their cause in the code

I tried to point configuration with the contents in the article and that the display is transmitted to the code (var_dump($this);), but there is no mention of the browser

my goal is to convey different browsers, and URLs in the configuration (for example, build and production)

or is there a way in phpunit how to pass a parameter "browser" in the console?

**Comment by giorgiosironi** [comment]
What you're looking for is `--boostrap` I think, which accepts a PHP file, while I've always seen `--config` used with the XML configuration and not with a base class.

**Comment by kantim** [comment]
Yes, --bootstrap <file> will use

1) make a boot.php file that contains variables:
$selenium_host    = '127.0.0.1';
$selenium_port    = '4444';

2) in the test cause the value:
global $selenium_host, $selenium_port;
$this->webdriver = RemoteWebDriver::create('http://' . $selenium_host. ':' . $selenium_port . '/wd/hub', $capabilities, 5000);
		
3) run: phpunit --bootstrap boot.php test.php
