### ISSUE TITLE
PHPUnit 5 compatibility

### ISSUE THREAD

**Issue by remicollet** [giorgiosironi/phpunit-selenium#351]
As new version should be released very soon, any ETA for a compatible version ?

**Comment by discopatrick** [comment]
I'm also interested :)

**Comment by giorgiosironi** [comment]
I'm in the process of getting the VM and the build running again, which needs some maintenance after new versions of Selenium and Firefox have come out. After that I will try running all the tests with PHPUnit 5 or dev-master and see what is missing...

**Comment by carlosbuenosvinos** [comment]
Ping!

**Comment by jeffminard-ck** [comment]
Specifically, this being out of sync is causing test failures for us:

https://github.com/giorgiosironi/phpunit-selenium/blob/master/PHPUnit/Extensions/SeleniumTestCase.php#L1109 

is incompatible with 

https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/TestCase.php#L1991

Which originated from

https://github.com/sebastianbergmann/phpunit/commit/240783375416032ab0dc18db3495bac0f300071a#diff-511c90242d5589e941582006e0485184L1900

**Comment by remicollet** [comment]
Any news about this ?

As PHPUnit.phar doesn"t includes anymore this extension, I'm thinking to also drop it from Fedora repository.

**Comment by cmb69** [comment]
From the current README.md:

> The current mainline of this package is 3.x, which supports PHPUnit 5.x.

So apparently this issue can be closed.

**Comment by giorgiosironi** [comment]
Yes, notice that it is a new major version, which removes the support for the very old Selenium 1 API.
