### ISSUE TITLE
No way to set sleep interval for waitUntil()

### ISSUE THREAD

**Issue by dominics** [giorgiosironi/phpunit-selenium#354]
`PHPUnit_Extensions_Selenium2TestCase_WaitUntil` declares `$_defaultSleepInterval` as `private`, and makes it 500ms. But there's no way to override this "default" (it should be called `$_hardcodedSleepInterval`!)

**Comment by giorgiosironi** [comment]
I agree it should be configurable, probably by adding an argument to `waitUntil()`. PRs are welcome.

**Comment by gsouf** [comment]
@giorgiosironi what about adding a configuration for ``$_defaultTimeout`` too? (PR on the way)

**Comment by giorgiosironi** [comment]
Ok with the static configuration method since PHPUnit gives no way to pass a configuration to the test objects, but I would prefer it to be on `Selenium2TestCase` to keep everything there?

**Comment by gsouf** [comment]
Got it
