### ISSUE TITLE
Missing SeleniumTestCase.php in version 2.0.1?

### ISSUE THREAD

**Issue by jhnferraris** [giorgiosironi/phpunit-selenium#372]
I've upgraded my phpunit composer

     "phpunit/phpunit": "4.2.*",
    "phpunit/php-invoker": "*",
    "phpunit/dbunit": ">=1.2",
    "phpunit/phpunit-selenium": ">=1.2",
    "phpunit/phpunit-story": "dev-master",

When I run my phpunit, It complains that `include(PHPUnit_Extensions_SeleniumTestCase.php): failed to open stream: No such file or directory`.

When I checked with the directories in `phpunit-selenium`, there is no SeleniumTestCase but Selenium2TestCase

Can anyone confirm? Are there any changes?

**Comment by giorgiosironi** [comment]
According to semantic versioning, major versions can break compatibility. Take a look at:
https://github.com/giorgiosironi/phpunit-selenium
and probably use `~1` instead.

**Comment by sitoshma** [comment]
To extend PHPUnit_Extensions_SeleniumTestCase we need to install "phpunit/phpunit-selenium": "~1.2",  from composer
Did you mean that?

**Comment by jhnferraris** [comment]
@sitoshma What I did was to use version `1.4.2` of phpunit-selenium just so SeleniumTestCase still exists. Since SeleniumTestCase was removed in version 2.0.1. 

Closing this..

**Comment by giorgiosironi** [comment]
Indeed, Selenium 1 is a very old protocol and it's also difficult to make it work with a modern PHPUnit. Therefore you can continue using `~1.4` to stay on the 1.x branch which still has the related class.

**Comment by sitoshma** [comment]
Ok 
I installed 
phpunit 4.0.2
phpunit-selenium 1.4.2
Still when i tried to run my script, I get this  issue
Configuration read from phpunit.xml.dist
<-[36;1ms<-[0m
............................., Skipped:1


** phpunit.xml.dist** file
  <php>
    <const name="PHPUNIT_TESTSUITE" value="true"/>
    <const name="PHPUNIT_TESTSUITE_EXTENSION_SELENIUM_HOST" value="127.0.0.1"/>
    <const name="PHPUNIT_TESTSUITE_EXTENSION_SELENIUM_PORT" value="4444"/>
    <const name="PHPUNIT_TESTSUITE_EXTENSION_SELENIUM_BROWSER" value="*firefox"/>
    <const name="PHPUNIT_TESTSUITE_EXTENSION_SELENIUM2_BROWSER" value="firefox"/>
    <const name="PHPUNIT_TESTSUITE_EXTENSION_SELENIUM_TESTS_URL" value="http://127.0.0.1:8080/"/>
    <const name="PHPUNIT_TESTSUITE_EXTENSION_SELENIUM_PATH" value="/tmp"/>
  </php>
