### ISSUE TITLE
Extensions_Selenium2TestCaseTest not found

### ISSUE THREAD

**Issue by reatang** [giorgiosironi/phpunit-selenium#376]
![image](https://cloud.githubusercontent.com/assets/8022923/14097609/7679d2a6-f5a5-11e5-930d-3b118d93e32b.png)

![image](https://cloud.githubusercontent.com/assets/8022923/14097616/8516628e-f5a5-11e5-9e94-259efbb8c6cb.png)

I think this class name is `PHPUnit_Extensions_Selenium2TestCase`

**Comment by giorgiosironi** [comment]
@gsouf hardcoded reference to a test class?

**Comment by gsouf** [comment]
auto completion mistake. I will fix it very fast
