### ISSUE TITLE
WebDriverException prior to handling alerts dialogs

### ISSUE THREAD

**Issue by seanirwin** [giorgiosironi/phpunit-selenium#382]
When a JavaScript alert is on the page I am unable to access the acceptAlert()/alertText()/declineAlert() methods, I can only test for expectedExceptions. Is there a way to switch to the alert dialog or other dialogs?

@expectedException PHPUnit_Extensions_Selenium2TestCase_WebDriverException
unexpected alert open

Java documentation suggest that you can switch to the alert window, but there doesn't seem to be a comparable method in the phpunit-selenium library.
driver.switchTo().alert();

**Comment by paulbriton** [comment]
I think you are trying to handle the alert too soon. 
I've made a [wrapper function](https://gist.github.com/paulbriton/c4dec3e900b1631039dbbd4ce92f885c) that's throw "unexpected alert open" exceptions and waits for getting the text of the alert. That's not the most elegant solution, but at least it works for my case.

**Comment by paulbriton** [comment]
Can also be closed, `switchTo()` command for alert isn't referenced in the [webdriver spec](https://www.w3.org/TR/webdriver/#user-prompts). 

Moreover, `alertIsPresent()` method has been added and should do what you want.
