### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by muhamed-didovic** [giorgiosironi/phpunit-selenium#383]
Anyone familiar with Basic Auth and how can I send username and password with selenium?

**Comment by giorgiosironi** [comment]
I would try the second solution here, modifying the URL to include username and password. It's the most portable:
http://stackoverflow.com/questions/24304752/how-to-handle-authentication-popup-with-selenium-webdriver-using-java

**Comment by muhamed-didovic** [comment]
Hi, thanks for quick reply.

So the situation is that inside HTML I have videos from third party(different domain), which require Basic Auth. Any ideas how to write inside that alert username and password?
