### ISSUE TITLE
Firefox v48 and Selenium 3.0.0-beta2 working together

### ISSUE THREAD

**Issue by muhamed-didovic** [giorgiosironi/phpunit-selenium#384]
Hi, 

I have updated Firefox to version v48 and now running tests with selenium is not working anymore.
So i have checked is there new version of selenium and there is Selenium 3.0.0-beta2,
but I can't make it working it together.

There is some kind of guide how to run and install Selenium 3.0.0-beta2:
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

I followed the instructions for MacOS and now when I run tests, Firefox is there but it can't open a page for testing.

Can anybody help?

**Comment by rbkoms** [comment]
hello!!

can u give a try with selenium-server-stanadalone-2.35.0.jar and firefox
from 20- 22 version. download the firefox 20 extract it and copy the
content of the firefox and paste it to the firefox under c drive or where u
have install....

**Comment by muhamed-didovic** [comment]
I can downgrade to Firefox v47, but I am asking have anyone tried Firefox 48 and Selenium v3.
Also should this library follow the release cycle of Selenium and Firefox?

**Comment by epoxa** [comment]
I use selenium-server-standalone-3.0.0-beta3 geckodriver v0.10.0 and phpunit v5.5.5
Permanently get an error: "There is currently no active session ..." and seems SetUp() method of my test cases not executing at all

**Comment by paulbriton** [comment]
From Firefox 48 you need to use the [Geckodriver](https://github.com/mozilla/geckodriver) which is enabled by default on Selenium 3.

**Comment by muhamed-didovic** [comment]
Hi @paulbriton, did you manage to get it working, if yes can you give us instructions so if anyone new comes with this question he can see this issue and solution for it

**Comment by paulbriton** [comment]
Yes I manage to get it working, it's the same installation as others drivers (e.g. Chromedriver and InternetExplorer Driver). 
You have to [download](https://github.com/mozilla/geckodriver/releases) the driver from the repo, and add it to your path environment, that's it.

You need to know that some commands aren't working (like `moveto()`) or aren't implemented yet (like `keys()`) but I hadn't test all of them for now.

**Comment by paulbriton** [comment]
This issue can be closed since there is no issue...
