### ISSUE TITLE
Implement Get Element Rect

### ISSUE THREAD

**Issue by paulbriton** [giorgiosironi/phpunit-selenium#387]
The `location()` function isn't in the WebDriver specifications and it isn't working for the Geckodriver. Is it possible to implement `rect()` function instead ? 

See https://www.w3.org/TR/webdriver/#get-element-rect for more details.

**Comment by giorgiosironi** [comment]
When Selenium 2 support was implemented https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol was the only available spec, but it's now been obsoleted by the W3 one. Would welcome a pull request, adding new elements should be feasible by just adding new classes and some configuration as they follow the Command pattern (inside the `PHPUnit_Selenium2TestCase_*` area).
