### ISSUE TITLE
Get all attributes or the html of an element?

### ISSUE THREAD

**Issue by samuraiseoul** [giorgiosironi/phpunit-selenium#389]
I need to see if some attributes changed since I can't use the equals function from the Element class to assert that an element has changed at all, besides just that the element is the same one that was on the page. Is there anyway to do this, or get the html, or anything?

**Comment by paulbriton** [comment]
This should do the trick : `$element->attribut('outerHTML');`

**Comment by paulbriton** [comment]
Issue can be closed as well.
