### ISSUE TITLE
selenium tests not working with phpunit laravel.

### ISSUE THREAD

**Issue by Aqeel222** [giorgiosironi/phpunit-selenium#402]
i want my phpunit tests to run with selenium. i started testing some days ago and facing a lot of trouble.

i am stuck in one thing. when i run my phpunit tests/abcTest.php i got error that selenium is not running on port 4444. please find my attached files also.

i created some tests using selenium IDE. please take a look at attached files.

i ran selenium server with "java -jar selenium-*.jar -port 4444" and output is also attached as file.

every time i got this output.

i am new in selenium though i worked with phpunit before.

this occurs when i try to create new session.
![2017-02-13_2015](https://cloud.githubusercontent.com/assets/17747266/22918164/c041e344-f2aa-11e6-9b7a-f119125b8e71.png)

this is how i run selenium.
![2017-02-13_2029](https://cloud.githubusercontent.com/assets/17747266/22918163/c0414aba-f2aa-11e6-94ed-1644f8f7d6cd.png)

my diresctory structure where selenium and drivers are
![2017-02-13_2106](https://cloud.githubusercontent.com/assets/17747266/22918165/c0454f5c-f2aa-11e6-870d-a62d47120edb.png)

selenium IDE created test case
![2017-02-13_2107](https://cloud.githubusercontent.com/assets/17747266/22918166/c0474fbe-f2aa-11e6-8d61-42383c931cd3.png)

error that selenium is not running on port 4444.
![2017-02-13_2109](https://cloud.githubusercontent.com/assets/17747266/22918167/c0489d2e-f2aa-11e6-91bb-b32c994026d7.png)

PHP version: 7.0.6
Selenium server version: 3.0.1
Operating system: windows 8.1
Browser used + version: chrome + 56.0.2924.87

**Comment by giorgiosironi** [comment]
I don't see anything that is obviously out of place, so I would suggest checking if Selenium is responding by running `curl -v localhost:4444` and if so, try to raise the debug level of the `java -jar` command to see if there is more helpful output.

**Comment by Aqeel222** [comment]
one thing i am confused in is i got  "Driver not found" error. please take a look below.
![2017-02-15_1127](https://cloud.githubusercontent.com/assets/17747266/22962942/f42229cc-f371-11e6-8f7f-8b06abb27544.png)

**Comment by paulbriton** [comment]
You need to add drivers (i.e. `chromedriver.exe` and `operadriver.exe`) in your system path. Then selenium will be able to detect them automatically. 

I think you can also specify drivers path through driver capabilities.

**Comment by Aqeel222** [comment]
i tried it also but same luck. Moreover i tried geckodriver for Mozilla Firefox. Test ran with no output. I see only blank page when test runs.

**Comment by paulbriton** [comment]
Are you sure that they're in your path ? Could you execute `echo %PATH%` in a windows command line ?

**Comment by Aqeel222** [comment]
yes i can. when i run "echo %PATH%" i get same drive name where all webDrivers are...

**Comment by paulbriton** [comment]
You're using MinGW in order to run the tests. Have you tried launching them with the windows command line ? Does MinGW share system path with windows ? 
It really looks like that there is a problem with your path.

**Comment by Aqeel222** [comment]
isn't it ok if i put all webDriver executables in the same directory as for selenium server.

**Comment by paulbriton** [comment]
Not it's not enough, that's what I told you before, they need to be present on your system path. So add your `C:\webDrivers` directory to your windows path. And try to launch test with windows command line.

**Comment by Aqeel222** [comment]
i will try it tomorrow now. working on other module of the project. will surely tell you in any luck.  thanks for your kindness
