### ISSUE TITLE
Interactions with elements which are present in DOM but not visible

### ISSUE THREAD

**Issue by ostrovanka** [giorgiosironi/phpunit-selenium#405]
How can I interact with such elements?
For now, as I see, each time I want to do something like
$element->getAttribute(); and this element is present but not visible I get an error:
Timed out waiting for element...

The problem is that each interaction with element leads to the call of the method findElement() from class Driver
and in this method we always wait for element visibility: $element->displayed()

How can I bypass this limitation and interact with all elements present in DOM (not only visible ones)

**Comment by giorgiosironi** [comment]
As far as I know, an explicit design decision of Selenium 2/Web Driver is to simulate what the user does, which means interacting only with visible elements. Not sure if this has ever changed to allow more actions.
