### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by remicollet** [giorgiosironi/phpunit-selenium#412]
phpunit-selenium requires:
*  "phpunit/phpunit": ">=6.0,<7.0",
*  "sebastian/comparator": "~1.0",

phpunit 6.3 requires
*  "sebastian/comparator": "^2.0.2",

Please update dependency on comparator, so latest phpunit can be used.

**Comment by giorgiosironi** [comment]
PHPUnit 6.0.8 seems to be the most up-to-date that can be used with the current master due to this issue.

**Comment by giorgiosironi** [comment]
Solved in master, releasing `4.1.0`.
