### ISSUE TITLE
vagrant provision failed on windows 

### ISSUE THREAD

**Issue by 4dsr** [giorgiosironi/phpunit-selenium#419]
Hi,
I had some problems with provision scripts. Lines ending with CRLF not LF. It leads to errors with massage containing "$'\r': command not found".
Runnig these two comands just before `vagrant up` or `vagrant provision` converts bash scripts to unix standard and solves the problem:
```
git config core.autocrlf false
dos2unix .ci/*
```

**Comment by zerkms** [comment]
It is your local git client problem: no scripts in `.ci` contain the `\r` (carriage return) character.

**Comment by 4dsr** [comment]
Never had such problem with vagrantbox before. Thanks.
