### ISSUE TITLE
PHPUnit_Extensions_Selenium2TestCase_WebDriverException: sendKeysToActiveElement 

### ISSUE THREAD

**Issue by Alex9179** [giorgiosironi/phpunit-selenium#420]
Hi, 

I've been using Selenium2 for a couple of years now and always with $this->keys('some text '); after clicking on an element, which worked fine. Recently however (without changing my use of keys()), this has thrown the exception in the title, is there any reason for this?

I thought it may have been as I was using a fairly dated set up, but now I've updated everything across the board and now run with the following:

- Firefox v57.0.4 (With Gecko)
- Java Server v3.8.1
- phpunit/phpunit-selenium 4.x
- PHP7.2
- phpunit/phpunit: "6.x"

I've come to the conclusion that it's no longer any of my versions, as the session is stared correctly and gets as far as clicking on the element I wish to use, but gets no further.

Thanks

**Comment by VD17593** [comment]
I've had a similar problem.

Also used Selenium2 for years, in a dated configuration.
Updated to:

- php 7.1
- php phpunit-6.5.5
- selenium-server-standalone-3.7.1
- phpunit-selenium 4.x

In previous configurations I used FireFox for testing.
But I didn't got the new configuration running with FireFox 57.0.3 (64-bit) and the most recent geckodriver.

However got it running with Crome 63.0 and the chromedriver.

**Comment by Alex9179** [comment]
And the keys() method worked? I can get it working with my new setup and written small tests to open pages and pick out elements to make sure the setup works, which is fine, it's just throwing the mentioned Exception when I try and send keys, which is a major issue as it means I cannot even log in to my system to test it!

**Comment by VD17593** [comment]
Everything works fine in the configuration I'm using with Chrome.

I'm still searching how to get it working with FireFox.

**Comment by Alex9179** [comment]
Yeah I've got it working for Chrome now, so will carry on with that, hopefully Firefox will be fixed soon!

**Comment by K-Deep** [comment]
I've had a similar problem.

keys() is working perfectly fine with chrome, IE but not for Firefox. I have tried almost all of the 3.x selenium version but no luck. Is this with php binding or selenium or gecko side.  Any workaround ?

**Comment by K-Deep** [comment]
I have further verified this with below versions and not working for any of these.

Selenium 3.4.0 + Firefox 49 + geckodriverv0.13.0, geckodriverv0.14.0, geckodriverv0.15.0
Selenium 3.4.0 + Firefox 52 + geckodriverv0.13.0, geckodriverv0.14.0, geckodriverv0.15.0
Selenium 3.8.1 + Firefox 52 + geckodriverv0.16.0, geckodriverv0.18.0, geckodriverv0.19.0, geckodriverv0.20.0
Selenium 3.8.1 + Firefox 56 + geckodriverv0.16.0, geckodriverv0.18.0, geckodriverv0.19.0, geckodriverv0.20.0
Selenium 3.8.1 + Firefox 58 + geckodriverv0.16.0, geckodriverv0.18.0, geckodriverv0.19.0, geckodriverv0.20.0

However it is working fine with Selenium 2.53 + Firefox 48.  I am using phpunit-selenium version 3.0.3 .

**Comment by K-Deep** [comment]
@Alex9179 @VD17593  any luck with firefox ?

**Comment by Alex9179** [comment]
Gave up on Firefox in the end, turned to Chrome and now use selenium 4 with chromedriver. Still hit the occassional issue with compatability though!

**Comment by K-Deep** [comment]
@giorgiosironi @sebastianbergmann Can you please provide any thoughts/ideas to work keys function with latest selenium.  If this is known issue , are we planning for any fixes ? I am really blocked due to this :(
