### ISSUE TITLE
Open headless Chrome

### ISSUE THREAD

**Issue by techhemant** [giorgiosironi/phpunit-selenium#429]
How can run Chrome in headless mode in PHPUnit_Extensions_Selenium2TestCase as there is no direct way to setting chromeoptions.

**Comment by LukeTowers** [comment]
@pajon you have no idea how long I've just spent scouring the web and digging deep into selenium, chrome, chromedriver documentation, not to mention the source of PHPUnit and PHPUnit_Selenium, plus playing around with direct CURL requests to the Selenium endpoint to try to get this working.

Your solution worked great, thanks so much!

**Comment by LukeTowers** [comment]
@czerwonyd See the above for how we can use headless chrome. Think about integrating it into your plugin as a part of the configuration that you'll be looking at.

**Comment by thewunder** [comment]
Even simpler
```php
$this->setDesiredCapabilities(['chromeOptions'=>['args'=>['headless']]]);
