### ISSUE TITLE
PHPUnit 8 support?

### ISSUE THREAD

**Issue by luckydonald** [giorgiosironi/phpunit-selenium#434]
Since earlier this year PHPUnit 8 is out, and 9 is already being worked on.

So after support for PHPUnit 7 #422 is almost released,
According to commit aa5eb9503269bb8a11760baf73d1a337ce072f93 it is still missing some parts for compatibility.

**Comment by luckydonald** [comment]
Oh, just found #432 related to that specific issue left to do.

**Comment by thewunder** [comment]
I'll help address this after we get 7 out the door

**Comment by KevP** [comment]
Any update?

**Comment by luckydonald** [comment]
@KevP 
So far @thewunder has not left feedback in #432, which needs to be addressed before we can have a 8+ version.

**Comment by pajon** [comment]
PHPUnit 8.x support https://github.com/giorgiosironi/phpunit-selenium/pull/441

**Comment by s0me0ther** [comment]
is there anything left to do?

confused why phpunit 8 is still not supported :/

**Comment by thewunder** [comment]
Thanks so much to @pajon for the great work!

**Comment by pajon** [comment]
Your welcome. Do we have a roadmap about what to next to do with this package ? For me is important to add support **PHPUnit 9.x** and do some changes to support also **w3c** protocol. But before we dive into w3c we need change architecture. I think will be good to migrate from dynamic handling commands (`__call` + annotations) like we use it now to more explicitly. Using less annotations (properties + methods) which can be messy if you need to understant how some code work. What do you think about it ?
