### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1 passed to PHPUnit_TextUI_TestRunner::doRun() must implement interface PHPUnit_Framework_Test, instance of PHPUnit_Exten sions_SeleniumTestSuite given

### ISSUE THREAD

**Issue by S-Arif** [giorgiosironi/phpunit-selenium#437]
Hi,

I am trying to use selenium with laravel and when i test it gives me error `Fatal error: Uncaught TypeError: Argument 1 passed to PHPUnit_TextUI_TestRunner::doRun() must implement interface PHPUnit_Framework_Test, instance of PHPUnit_Exten
sions_SeleniumTestSuite given, called in C:\xampp\php\pear\PHPUnit\TextUI\Command.php on line 176 and defined in C:\xampp\php\pear\PHPUnit\TextUI\TestRunner.php:13
7
Stack trace:
#0 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Extensions_SeleniumTestSuite), Array)
#1 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(129): PHPUnit_TextUI_Command->run(Array, true)
#2 C:\xampp\php\phpunit(46): PHPUnit_TextUI_Command::main()
#3 {main}
  thrown in C:\xampp\php\pear\PHPUnit\TextUI\TestRunner.php on line 137`
Can you please rectify this error and it's solution? i didn't found any resource for this error over internet.

Looking forward to a solution.

**Comment by thewunder** [comment]
@S-Arif Sounds like you just need to extend PHPUnit_Framework_Test in your test class
