### ISSUE TITLE
Chromium Edge browser implementation issue with phpunit-selenium

### ISSUE THREAD

**Issue by y123sing** [giorgiosironi/phpunit-selenium#440]
**Environment**
OS: Windows 10 (64 bit)
Browser: Microsoft Chromium Edge
Browser version: Version 79.0.309.40 (Official build) beta (64-bit)
Browser Driver version:  79.0.309.40
Language Bindings version: PHP 7.3.3
Selenium Webdriver version: selenium-server-standalone-3.8.1

**Running chromium edge web driver**
java -Dwebdriver.edge.driver=msedgedriver.exe -jar selenium-server-standalone-3.8.1.jar

**Issue**

I am facing an issue while setting binary path for Chromium edge browser
Below is java code example to set binary path for the same

ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.setBinary(
                "C:\\Program Files (x86)\\Microsoft\\Edge Dev\\Application\\msedge.exe");
        EdgeOptions edgeOptions = new EdgeOptions().merge(chromeOptions);
        driver = new EdgeDriver(edgeOptions);

Is there any way i can set the same with PHPUnit-Selenium

**Comment by pajon** [comment]
Hello y123sing,

i think call `PHPUnit_Extensions_Selenium2TestCase::setBrowser()` with property value could help.

Try call with value 'internet explorer' or 'chrome'. [https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities](url)
