### ISSUE TITLE
PHPUnit 9 Support

### ISSUE THREAD

**Issue by drsassafras** [giorgiosironi/phpunit-selenium#447]
Is there a timeline or plan to integrate PHPUnit 9 support?

**Comment by pajon** [comment]
Hi @drsassafras 
I can do it, but first I need to finish some refactorings. Also guys with permission must approve it.

**Comment by drsassafras** [comment]
That is fantastic! I see commits are being made to the code somewhat regularly, so seems like getting good pull requests approved shouldn't be too difficult.

**Comment by pajon** [comment]
@drsassafras #448 😎

**Comment by pajon** [comment]
PHPUnit 9 support was merged into master.
